server:
  port: 8083

spring:
  application:
    name: inf-api-gateway-server
  datasource:
    url: jdbc:mysql://192.168.64.75:3306/waf?characterEncoding=utf-8&autoReconnect=true
    username: waf
    password: Waf123!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    removeAbandoned: false
    removeAbandonedTimeout: 1800
    logAbandoned: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;druid.stat.logSlowSql=true

logging:
  level:
    root: INFO
    cc:
      seedland: DEBUG
  file: logs/access.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    mapper-locations: classpath*:mappers/**/*.xml

